officeQuotes = [
  "Sometimes I'll start a sentence and I don't even know where it's going. I just hope I find it along the way. — Michael Scott",
  "I talk a lot, so I've learned to just tune myself out... — Kelly Kapoor",
  "I am Beyonce always. — Michael Scott",
  "Oh, it is on, like a prawn who yawns at dawn. — Andy Bernard",
  "I am running away from my responsibilities and it feels good. — Michael Scott",
  "Should have burned this place down when I had the chance. — Michael Scott",
  "One day Michael came in and complained about a speed bump on the highway. I wonder who he ran over then. — Jim Halpert",
  "Mini cupcakes? As in the mini version of regular cupcakes? Which is already a mini version of cake? Honestly, where does it end with you people? — Kevin Malone",
  "I don't care what they say about me. I just want to eat. — Pam Beesly",
  "Would I rather be feared or loved? Easy. Both. I want people to be afraid of how much they love me. — Michael Scott",
  "Whenever I'm about to do something, I think, 'Would an idiot do that?' and if they would, I do not do that thing. — Dwight Schrute",
  "I stopped caring a long time ago. — Creed Bratton",
  "It takes an advanced sense of humor. I don't expect everybody to understand. — Michael Scott",
  "The doctor said, if I can't find a new way to relate more positively to my surroundings, I'm going to die. I'm going to die. — Stanley Hudson",
  "I'm not superstitious, but I am a little stitious. — Michael Scott",
  "You only live once? False. You live every day. You only die once. — Dwight Schrute",
  "Bears, beets, Battlestar Galactica. — Jim Halpert",
  "I understand nothing. — Michael Scott",
  "What are your weaknesses?" "I don't have any, a--hole. — Kelly Kapoor",
  "I got six numbers. One more would have been a complete telephone number. — Kevin Malone",
  "For my new year's resolution, I gave up drinking... during the week. — Meredith Palmer",
  "Come on guys. Early worm gets the worm." "Another worm, like, are they friends? —Michael Scott and Jim Halpert",
  "An office is a place where dreams come true. — Michael Scott",
  "I wish there was a way to know you're in the good old days before you've actually left them. — Andy Bernard",
  "I am one of the few people who looks hot eating a cupcake. — Kelly Kapoor",
  "If I don't have some cake soon, I might die. — Stanley Hudson",
  "I knew exactly what to do, but in a much more real sense I had no idea what to do. — Michael Scott",
  "Sorry I annoyed you with my friendship. — Andy Bernard",
  "I just wanna lie on the beach and eat hot dogs. That's all I've ever wanted. — Kevin Malone",
  "That's what she said. — Michael Scott",
  "Guess what, I have flaws. What are they? Oh, I don't know. I sing in the shower. Sometimes I spend too much time volunteering. Occasionally I'll hit somebody with my car. So sue me... No, don't sue me. That is the opposite of the point that I'm trying to make. — Michael Scott"
]
